name: Plan and Apply terraform in "terraform/**"

on: 
    workflow_dispatch:              # allows the job to be manually triggered
    push:                            
        branches: [main]            # This action is triggered if there is a push to main
        paths: ["terraform/**"]     # specifically in the terraform directory
    
    pull_request:                   # also trigerred by pull requests
        branches: [main]
        paths: ["terraform/**"]

jobs:
    plan:
        name: Terraform plan
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          contents: read

        steps:
            - uses: .github/actions/terraform-setup
              with:
                role-to-assume: arn:aws:iam::923377182840:role/GithubActions-Terraform-Learning
                aws-region: us-east-1

            - name: Initialize project and view Terraform Plan
              run: |
                cd terraform
                terraform fmt
                terraform init
                terraform plan

    deploy:
        name: Terraform deploy
        needs: plan
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        permissions:
          id-token: write
          contents: read
          
        steps:
            - uses: .github/actions/terraform-setup
              with:
                role-to-assume: arn:aws:iam::923377182840:role/GithubActions-Terraform-Learning
                aws-region: us-east-1
            - name: Initialize project and deploy terraform
              run: |
                cd terraform
                terraform fmt
                terraform init
                terraform apply --auto-approve=true